# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export PATH=$PATH:~/.composer/vendor/bin

#ALIASES
alias art='valet php artisan'
alias artc="art clear-compiled && art cache:clear && art route:clear && art config:clear && valet composer dumpautoload && art view:clear"
alias aql="art queue:listen --tries=3"
alias tink="art tinker"
alias ting='valet php artisan tinker ting.php'
alias w="yarn install && rm -rf public/js && rm -rf public/css && npm run dev -- --display none"
alias wp="yarn install && rm -rf public/js && rm -rf public/css && npm run prod"
alias ww='rm -rf public/js && rm -rf public/css && npm run watch -- --display none'
alias wrh='rm -rf public/js && rm -rf public/css && npm run hot'
alias rrevent="art dev:get-active-event"
alias phpunit_fix="vendor/bin/php-cs-fixer fix"
alias vim="nvim"
alias lg="Lazygit"

ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

eval "$(starship init zsh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
